### ISSUE TITLE
dotnet core 2.1 support

### ISSUE THREAD

**Issue by jesseomega** [lecaillon/Evolve#69] opened 2018-07-18 14:32 UTC
My app needs to move to dotnet core 2.1, but getting the following error against Evolve 1.8.0 at the end of this note.

I've tried to work around this building it myself. I pulled down the latest master source targeting for 1.9.0-alpha, added NETCORE to the conditional compilation parameters under the Evolve project, and retargeted it to netcoreapp2.1. Added the following NuGet dependencies:
Microsoft.Build.Framework (15.7.179)
Microsoft.Build.Utilities.Core (15.7.179)
Microsoft.Extensions.DependencyModel (2.1.0)
Newtonsoft.Json (11.0.2)
System.Configuration.ConfigurationManager (4.5.0)
System.Data.Common (4.3.0)

I was then able to build the Evolve project and published a package to my own repo for use. It runs as a function of the app, but I also use the evolve.json so that it runs the migration at build time. This trigger seems to not be working. I get no logging output. I can be patient to wait for proper 2.1 support from you, but I need a work around for the build triggering. Any ideas? Thanks!

Evolve : error : EvolveException: Validation of the database connection failed. Could not load file or assembly 'System.Security.Permissions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER)) 
Evolve : error :    at Evolve.Connection.WrappedConnection.Validate()
Evolve : error :    at Evolve.Evolve.InitiateDatabaseConnection()
Evolve : error :    at Evolve.Evolve.InternalExecuteCommand(Action`1 commandAction)
Evolve : error :    at Evolve.MsBuild.EvolveBoot.Execute()
Evolve : error : FileLoadException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Invalid pointer (Exception from HRESULT: 0x80004003 (E_POINTER))
Evolve : error :    at MySql.Data.MySqlClient.MySqlConnection.AssertPermissions()
Evolve : error :    at MySql.Data.MySqlClient.MySqlConnection.Open()
Evolve : error :    at Evolve.Connection.WrappedConnection.Open()
Evolve : error :    at Evolve.Connection.WrappedConnection.Validate()
Evolve : error : ArgumentNullException: Value cannot be null.
Evolve : error : Parameter name: lib 
Evolve : error :    at Evolve.Utilities.Check.NotNull[T](T reference, String parameterName)
Evolve : error :    at Evolve.Driver.CoreReflectionBasedDriverEx.GetManagedAssembliesFullPath(RuntimeLibrary lib)
Evolve : error :    at Evolve.Driver.CoreReflectionBasedDriverEx.CustomAssemblyLoader.CustomAssemblyLoader_Resolving(AssemblyLoadContext context, AssemblyName assemblyName)
Evolve : error :    at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssembly(AssemblyName assemblyName) 
Evolve : error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
Evolve : error :    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
Evolve : error :

**Comment by jesseomega** [comment] 2018-08-17 21:18
MySql.Data 8.0.11

**Comment by lecaillon** [comment] 2018-08-23 09:36
Ok, nice. I'm on it too ;) 
It seems the VisualStudio building part is still working, but the `dotnet build` part is not. 
I reproduced your issue. Some `compileOnly` dependencies are not loaded by default anymore in NetCore2.1
I hope I have a fix soon this week or the next one.

**Comment by jesseomega** [comment] 2018-08-23 20:08
Mind checking out this pull request. I just put it against my fork so that you could review it. I haven't figured out how to run your test environment quite yet. I have docker installed, but I guess I haven't set it up correctly.

https://github.com/jesseomega/Evolve/pull/1

My thought is that the custom assembly loader you have, isn't pulling everything in as it should? Really at a loss. Migrations at runtime, and through dotnet build work, but building within visual studio fails. Full details are in the text of the pull request. Thanks!

**Comment by jesseomega** [comment] 2018-08-24 04:58
https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/

Looks like these msbuild tasks are particularly tricky to make happy. Any suggestions for a better long term strategy? You recommended creating a console app that uses the in app mode, runs the migrations and exits? It’s a shame this is so fragile, as I find the build time migrations triggered from the presence of the evolve.json file to be a nice feature!

Is there something easy you can suggest for resolving this missing dependency? I’ve tried several things adding the missing library as a package reference in the project file for the build targets as well as adding to the nuspec, no change, added it to the copy to build folder section to copy the dll as you do for system.common.data. I’ve added logging to see what what is being called during the visual studio build, and I observe it’s running the NET452 and IsStandard code paths. I’ve added logging of the dependencies and types that are loaded when loading the mysqlconnector library before it throws the exception, and I only see the MySqlConnector driver assembly loading. The assemblies and dependencies lists seem to be empty under this object.... I’ve tried a lot of different things, trying to find some light in these dark corners. Definitely lost some sleep on this one.

**Comment by lecaillon** [comment] 2018-08-24 19:19
Thanks for your efforts. Rest assured I totally understand what you mean by _losting some sleep_ understanding how to load assemblies in NetCore... The thing is clearly not _(enough?)_ documented.
And loading them from a MSBuild task is a nice challenge too ;)
Anyway I'm confident. I'm currently working on it too. 
Most of the work concerns the class `CoreReflectionBasedDriverEx`. Where I did not do anything about *compileOnly* dependencies by the past, I try to load them too now.
I'll keep you informed when I will have some news. Soon I hope.

For the tests, you don't have to do anything special to launch them. Just DockerForWindows installed and run the test you want in VisualStudio. (The first time, it can take some time due to the fact it must pull the database Docker image from the repo.)

**Comment by lecaillon** [comment] 2018-08-25 01:11
Well I was able to make SqlServer, SQLite, PostgreSQL and Cassandra work with NetCore 2.1 but still have an issue with MySql.Data driver... It works on Windows (Visual Studio + `dotnet build`) but not on Linux. 

> EvolveException: Validation of the database connection failed. Could not load file or assembly 'System.Security.Permissions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

I'm pretty sure I load the assembly. In debug mode on Windows this is the case at least...
If you only build your projects on Windows you can test this [package](https://ci.appveyor.com/api/buildjobs/d2y8a15hj92700nf/artifacts/dist%2FEvolve.1.9.0-alpha.nupkg)

I think I will make a pause for a while on this driver... and try to implement the [MySqlConnector](https://mysql-net.github.io/MySqlConnector/), hoping that at least one driver can be compatible with Evolve and the MSBuild mode on NetCore 2.1

**Comment by jesseomega** [comment] 2018-08-25 04:43
Had to set UseAffectedRows=false in the connection settings with MySqlConnector to act equivalently to MySql.Data.

**Comment by lecaillon** [comment] 2018-08-26 23:31
It seems I finally find a way to make the MySql.Data driver works in Evolve. 
Anyway I will add support of the MySqlConnector too in the next release.

**Comment by jesseomega** [comment] 2018-08-27 04:16
I see that, thank you! I was testing out your 2.1 branch as you were making updates :) Look forward to the MySqlConnector support.

I've been trying to brute force in this missing library dependency, but there's something very strange about how System.Memory and its dependencies on System.Buffers and System.Runtime.CompilerServices.Unsafe are linked in. The System.RuntimeCompilerServices.Unsafe appears to be the current problem. I'm guessing it's yet a another strange corner case of your custom assembly loader? I'm failing to make progress :(

**Comment by lecaillon** [comment] 2018-08-27 17:55
Addressed by #73

**Closed** 2018-08-27 17:56 UTC
Labels: MySQL, bug
