### ISSUE TITLE
MSBuild task targeting postgresql fails in a netcoreapp2.1 project

### ISSUE THREAD

**Issue by shrayasr** [lecaillon/Evolve#83] opened 2018-09-14 11:44 UTC
## Description

Evolve MSBuild task fails when targeting postgresql with the following error:

```
EvolveException: 
  Validation of the database connection failed. Method not found: 
    'Void System.Runtime.CompilerServices.Unsafe.WriteUnaligned(Byte ByRef, Int32)
```

Project Type: `ASP .Net Core web app` 
Framework: `.Net Core 2.1`
Evolve: `Evolve 1.8.0`
Driver: `Npgsql 4.0.3`
OS: `Windows 10`

## Steps to reproduce error

- Create a new **ASP .Net Core Web Application** project
- Choose **Web Application (Model-View-Controller)** in the wizard
- Add Evolve via `install-package evolve`
- Add Npgsql via `install-package npgsql`
- Add a empty `Migrations` folder to the root of the project
- Add an `evolve.json` file as shown below
- Build (The error occurs here)

```
{
  "Evolve.ConnectionString": "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=learning;",
  "Evolve.Driver": "Npgsql",
  "Evolve.Locations": "Migrations",
  "Evolve.Command": "migrate"
}
```

Repo: https://github.com/shrayasr/EvolvePGWebIssue

**Note:** I removed `evolve.json` and ran it in-app and things worked fine. So proceeding with that for now.

## Additional info

There seems to have been a similar problem in #69 as well. Although I found [this comment](https://github.com/lecaillon/Evolve/issues/69#issuecomment-416109694) very close to the problem that this issue brings up. Quoting section here: 

> there's something very strange about how System.Memory and its dependencies on System.Buffers and System.Runtime.CompilerServices.Unsafe are linked in. The System.RuntimeCompilerServices.Unsafe appears to be the current problem. I'm guessing it's yet a another strange corner case of your custom assembly loader?

---

PS: Thank you for putting your time in and writing this wonderful library. We use it at the heart of all our applications at @logicsoftind. Thank you! ✨ 🙏 ✨

**Comment by lecaillon** [comment] 2018-09-14 17:12
Thanks for your feedback. It is always a pleasure to know Evolve can be useful to somebody 😁
Very soon the version 1.9.0 will be released and should fix your issue.
Meanwhile you could try the alpha version which is very closed to the final. 
https://ci.appveyor.com/api/buildjobs/gl5cnnvhpv8ip5ub/artifacts/dist%2FEvolve.1.9.0-alpha.nupkg

**Comment by shrayasr** [comment] 2018-09-15 05:41
> Thanks for your feedback. It is always a pleasure to know Evolve can be useful to somebody 😁

Its important that we let maintainers know this. I'm sure y'all have bad days. Thanks again, Philippe 🙋 

> Very soon the version 1.9.0 will be released and should fix your issue.
> Meanwhile you could try the alpha version which is very closed to the final.

I will try this and get back 👍

**Comment by lecaillon** [comment] 2018-10-10 20:31
The very soon moment is arrived... Feel free to try the Evolve 1.9.0. It should fix your issues

**Comment by lecaillon** [comment] 2018-11-09 14:41
I think the issue is fixed. If not feel free to open a new issue about it.

**Closed by lecaillon** 2018-11-09 14:41 UTC
